added docker file
RelevanceAI/RelevanceAI pull request #268
Opened 2022-01-14 08:39 UTC by felixzhu17

docker build -t python-relevanceai .

2022-01-14 11:35 UTC, boba-and-beer requested changes

2022-01-14 11:35 UTC, boba-and-beer commented on Dockerfile
> +FROM python:3.8
hey who'd you choose python3.8

2022-01-14 11:35 UTC, boba-and-beer commented on Dockerfile
> +RUN python setup.py install
pip install -e .[viz] or something. It should have everything if possible

2022-01-14 11:35 UTC, boba-and-beer commented on Dockerfile
> +CMD ["python"]
nah no need for this I reckon

2022-01-18 04:10 UTC, felixzhu17 commented on Dockerfile
> +FROM python:3.8
which python do you want?

2022-01-19 02:29 UTC, boba-and-beer commented on Dockerfile
> +FROM python:3.8
3.7 for now please

2022-01-19 14:30 UTC, boba-and-beer commented
- Missing .dockerignore 
- Not sure where docker container is hosted 
- Missing build instructions in README
- Missing Jupyter notebook env if possible 

Closing for now. Will return to this later.

2022-01-19 14:30 UTC, closed without merging